version: "3.7"

services:

  web:
    image: nginx:1.17
    ports:
      - 80:80
    volumes:
      - ${HOME}/docker-study/recipe-01/html:/var/www/myapp
      - ${HOME}/docker-study/recipe-01/docker/default.conf:/etc/nginx/conf.d/default.conf
